version: '3'

services:
  application_geo_db:
    container_name: application_geo_db
    image: redis:latest
    ports:
      - $REDIS_PORT:$REDIS_PORT

  application_db:
    container_name: application_db
    image: postgres:latest
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - application_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata

  db_management_service:
    build:
      context: ./dbmanagement
      dockerfile: Dockerfile
    image: db_management
    depends_on:
      - application_db
    environment:
      - JDBC_DATABASE_USERNAME=$POSTGRES_USER
      - JDBC_DATABASE_PASSWORD=$POSTGRES_PASSWORD
      - JDBC_DATABASE_URL=jdbc:postgresql://application_db:$DB_PORT/$POSTGRES_DB

  stop_marshrutka_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: stop_marshrutka
    depends_on:
      - db_management_service
      - application_geo_db
    ports:
      - $APPLICATION_PORT:$APPLICATION_PORT
    environment:
      - JDBC_DATABASE_USERNAME=$POSTGRES_USER
      - JDBC_DATABASE_PASSWORD=$POSTGRES_PASSWORD
      - JDBC_DATABASE_URL=jdbc:postgresql://application_db:$DB_PORT/$POSTGRES_DB

volumes:
  application_db: {}